### ISSUE TITLE
TkAstroDb.py does not exist in your folders (Instaed I see run.py)

### ISSUE THREAD

**Issue by DarthRecca** [dildeolupbiten/TkAstroDb#1]
Sir, I appreciate your contribution and must mention this is an excellent help for all those who want to do research.
I however request you to make TkAstroDb.py available for us to download and run as per your documentation. I see run.py available in folder. Is this the same program file that you want us to run?

**Comment by dildeolupbiten** [comment]
Yes, `run.py` is the file you should run. Sorry I haven't changed the `README.md` file yet. The old `README.md` was written 2 years ago. But I am writing a new `README.md` that I hope it helps the users.

**Comment by dildeolupbiten** [comment]
The program is updated to version 2.2.0 which contains the new `README.md` file. And this issue is closed.
